version: "3.8"

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.app
    expose:
      - "8501"
  
  nginx:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    depends_on:
      - app